import type { Express } from "express";
import type { AppConfig } from "../config/appConfig.js";
import type { AuthorizedUserRepository } from "../core/auth/authorizedUserRepository.js";
import type { AccessControl } from "../core/auth/accessControl.js";
import type { ClarificationPlanner } from "../core/clarifications/clarificationPlanner.js";
import type { DeployService } from "../core/deployment/deployService.js";
import type { LiveVerifier } from "../core/deployment/liveVerifier.js";
import type { BaseTemplateSelector } from "../core/generation/baseTemplateSelector.js";
import type { CodexRunner } from "../core/generation/codexRunner.js";
import type { FeatureModuleSelector } from "../core/generation/featureModuleSelector.js";
import type { GenerationPlanner } from "../core/generation/generationPlanner.js";
import type { RepairLoop } from "../core/generation/repairLoop.js";
import type { JobRepository } from "../core/jobs/jobRepository.js";
import type { JobManager } from "../core/jobs/jobManager.js";
import type { JobQueue } from "../core/jobs/jobQueue.js";
import type { JobRunner } from "../core/jobs/jobRunner.js";
import type { TelegramNotifier } from "../core/notifications/telegramNotifier.js";
import type { PendingEditRequestRepository } from "../core/projects/pendingEditRequestRepository.js";
import type { PendingRollbackRequestRepository } from "../core/projects/pendingRollbackRequestRepository.js";
import type { ProjectManager } from "../core/projects/projectManager.js";
import type { AppProjectRepository } from "../core/projects/projectRepository.js";
import type { ProjectStorage } from "../core/projects/projectStorage.js";
import type { AppRevisionRepository } from "../core/revisions/revisionRepository.js";
import type { FeasibilityChecker } from "../core/specs/feasibilityChecker.js";
import type { SpecExtractor } from "../core/specs/specExtractor.js";
import type { TelegramBot } from "../core/telegram/telegramBot.js";
import type { TelegramMessageReferenceRepository } from "../core/telegram/telegramMessageReferenceRepository.js";
import type { TelegramAdminUseCases, TelegramBuildUseCases } from "../core/telegram/telegramUseCases.js";
import type { ArtifactStore } from "../core/workspaces/artifactStore.js";
import type { WorkspaceCustomizer } from "../core/workspaces/workspaceCustomizer.js";
import type { WorkspaceManager } from "../core/workspaces/workspaceManager.js";
import type { BuildRunner } from "../core/validation/buildRunner.js";
import type { SmokeTester } from "../core/validation/smokeTester.js";
import type { Validator } from "../core/validation/validator.js";
import type { DbClient } from "../db/client.js";
import type { CodexClient } from "../integrations/codex/codexClient.js";
import type { TelegramClient } from "../integrations/telegram/telegramClient.js";
import type { VercelClient } from "../integrations/vercel/vercelClient.js";

export type RiclawServices = {
  config: AppConfig;
  httpApp: Express;
  dbClient: DbClient;
  jobRepository: JobRepository;
  projectRepository: AppProjectRepository;
  revisionRepository: AppRevisionRepository;
  pendingEditRequestRepository: PendingEditRequestRepository;
  pendingRollbackRequestRepository: PendingRollbackRequestRepository;
  telegramMessageReferenceRepository: TelegramMessageReferenceRepository;
  authorizedUserRepository: AuthorizedUserRepository;
  accessControl: AccessControl;
  jobManager: JobManager;
  jobQueue: JobQueue;
  jobRunner: JobRunner;
  projectManager: ProjectManager;
  projectStorage: ProjectStorage;
  telegramClient: TelegramClient;
  telegramNotifier: TelegramNotifier;
  telegramBuildUseCases: TelegramBuildUseCases;
  telegramAdminUseCases: TelegramAdminUseCases;
  telegramBot: TelegramBot;
  codexClient: CodexClient;
  specExtractor: SpecExtractor;
  feasibilityChecker: FeasibilityChecker;
  baseTemplateSelector: BaseTemplateSelector;
  featureModuleSelector: FeatureModuleSelector;
  workspaceManager: WorkspaceManager;
  workspaceCustomizer: WorkspaceCustomizer;
  artifactStore: ArtifactStore;
  generationPlanner: GenerationPlanner;
  codexRunner: CodexRunner;
  buildRunner: BuildRunner;
  smokeTester: SmokeTester;
  validator: Validator;
  repairLoop: RepairLoop;
  clarificationPlanner: ClarificationPlanner;
  vercelClient: VercelClient;
  deployService: DeployService;
  liveVerifier: LiveVerifier;
};
